name: Pre-test
on:
  push:
    branches:
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Lint code
      run: |
        pip install pre-commit
        pre-commit run --all-files
    - name: Test code
      run: |
        pip install poetry
        poetry install
        poetry run pytest
